/* eslint-disable react/no-unescaped-entities */
import React, { FC, useEffect, useState } from 'react'
import { OverlayScrollbarsComponent } from 'overlayscrollbars-react'

interface IHowItWorks {}

const HowItWorks: FC<IHowItWorks> = () => {
  const [maxHeight, setMaxHeight] = useState('40rem')

  useEffect(() => {
    const handleResize = () => {
      if (window.innerWidth <= 991.98) {
        setMaxHeight('94.7vh')
      } else {
        setMaxHeight('40rem')
      }
    }

    handleResize()
    window.addEventListener('resize', handleResize)

    return () => window.removeEventListener('resize', handleResize)
  }, [])

  return (
    <div className="flex-1  rounded-12xs bg-black font-ocrx border-forestgreen border-[.1875rem] border-solid box-border flex flex-col md:max-h-[40rem]">
      <OverlayScrollbarsComponent options={{}} style={{ maxHeight, overflow: 'auto' }}>
        <div className="flex flex-col gap-[1.668rem]">
          <div className="flex flex-col gap-6 md:gap-[2.375rem] md:p-10 px-4 py-6 ">
            <div className="tracking-[-0.06em] leading-[1.313rem] text-2xl">## HOW IT WORKS</div>
            <div className="flex flex-col gap-[2.375rem]">
              <div className="flex flex-col gap-4">
                <div className="text-2xl">
                  <span>[ Step 1 | </span>
                  <span className="text-fuchsia">Bridge Bitcoin to Bitlazer</span>
                  <span> ] </span>
                </div>
                <div className="tracking-[-0.06em] leading-[1.313rem] font-maison-neue">
                  Users can bridge their Wrapped Bitcoin (WBTC) from Ethereum to Bitlazer's Layer 3 (L3) network, or
                  directly deposit native Bitcoin (BTC) using the BTC-native bridge, powered by light client technology.
                  This process securely transfers assets to the L3 Bitlazer network, where they can participate in
                  decentralized applications (dApps).
                </div>
              </div>
              <div className="flex flex-col gap-4">
                <div className="text-2xl">
                  <span>[ Step 2 | </span>
                  <span className="text-fuchsia">Stake L3 BTC or LZR Tokens</span>
                  <span> ] </span>
                </div>
                <div className="tracking-[-0.06em] leading-[1.313rem] font-maison-neue">
                  <p className="m-0">
                    Once assets are bridged, users can participate in Bitlazer’s dual staking rewards program. They have
                    the option to stake either:
                  </p>
                  <p className="m-0">/ L3 BTC, earning rewards in Bitlazer's native token, LZR.</p>
                  <p className="m-0">
                    / LZR Tokens, earning both governance rights and a share of the gas fees generated by the platform,
                    paid in BTC.
                  </p>
                </div>
              </div>
              <div className="flex flex-col gap-4">
                <div className="text-2xl">
                  <span>[ Step 3 | </span>
                  <span className="text-fuchsia">Claim Airdrop and Earn Yield</span>
                  <span> ] </span>
                </div>
                <div className="tracking-[-0.06em] leading-[1.313rem] font-maison-neue">
                  <p className="m-0">
                    Users who bridge their BTC and actively participate in staking can also qualify for the airdrop of
                    LZR tokens. Early bridgers receive an additional 20% bonus from the total LZR supply allocated for
                    the airdrop, incentivizing active engagement and early adoption of the Bitlazer ecosystem.
                  </p>
                  <p className="m-0">
                    These steps ensure that users not only receive staking rewards but also benefit from the LZR
                    airdrop, maximizing their participation in the Bitlazer network’s growth.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </OverlayScrollbarsComponent>
    </div>
  )
}

export default HowItWorks
