name: Tests
on:
  push:
    paths:
      - 'contracts/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        run: |
          curl -L https://unpkg.com/@pnpm/self-installer | node
          echo 'export PATH=$HOME/.pnpm/bin:$PATH' >> $GITHUB_ENV

      - name: Read .nvmrc
        run: echo NVMRC=`cat .nvmrc` >> $GITHUB_ENV

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NVMRC }}

      - run: pnpm install
      - run: pnpm contracts:compile
      - run: pnpm contracts:test
